- name: Install necesary library
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - libssl-dev

- name: Load NodeJS 7.x
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

- name: Install NodeJS
  apt: pkg=nodejs state=latest